### ISSUE TITLE
Helps me on Build but not on Start

### ISSUE THREAD

**Issue by ruslanguns** [bastidest/context-map-webpack-plugin#1]
Thanks for this library which helps us to build files with webpack however I am not able to start my stack with `node dist/server` which gets me the same issue:

```bash
Error: Cannot find module '../lib/utils.js'
```

**Comment by bastidest** [comment]
Can you provide more context on where the module is imported from? Maybe post the whole error without sensitive information.

**Comment by ruslanguns** [comment]
Thanks for your quick reply.

On build I was getting error with `Error: Cannot find module '../lib/utils.js'` then I've setup this library and it allowed me to build. However my stack is not able to start on production since `node dist/server´script is broken with the lack of this module route.

Here's my project: You can find the Webpack settings just in the root: 'webpack.server.config.js'
https://github.com/ruslanguns/bikes-showcase/tree/bug/webpack

**Comment by bastidest** [comment]
Can your provide a state **before** using the plugin? I compiled your page without the plugin and there were no errors. I want to see the particular "critical dependency" webpack error. The plugin will only work with this type of error.

**Comment by ruslanguns** [comment]
I am going to close this issue since I think your plugin is enough for me for compile the code, and for start production I will use a different approach for now. Thanks for your help.
